### ISSUE TITLE
[Bug]: Package incompatible with spatie/laravel-permissions

### ISSUE THREAD

**Issue by Temepest74** [kiwilan/typescriptable-laravel#21]
### What happened?

I get this error when I run ```sail artisan typescriptable:models```
```
Kiwilan\Typescriptable\Typed\Eloquent\Utils\EloquentProperty::__construct(): Argument #3 ($type) must be of type string, null given, called in /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/EloquentItem.php on line 135 {"exception":"[object] (TypeError(code: 0): Kiwilan\\Typescriptable\\Typed\\Eloquent\\Utils\\EloquentProperty::__construct(): Argument #3 ($type) must be of type string, null given, called in /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/EloquentItem.php on line 135 at /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/Utils/EloquentProperty.php:10)
[stacktrace]
#0 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/EloquentItem.php(135): Kiwilan\\Typescriptable\\Typed\\Eloquent\\Utils\\EloquentProperty->__construct()
#1 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/EloquentItem.php(63): Kiwilan\\Typescriptable\\Typed\\Eloquent\\EloquentItem->setProperties()
#2 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Utils/ClassItem.php(42): Kiwilan\\Typescriptable\\Typed\\Eloquent\\EloquentItem::make()
#3 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/Utils/ClassItem.php(68): Kiwilan\\Typescriptable\\Typed\\Utils\\ClassItem::make()
#4 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typed/EloquentType.php(44): Kiwilan\\Typescriptable\\Typed\\Utils\\ClassItem::list()
#5 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Typescriptable.php(13): Kiwilan\\Typescriptable\\Typed\\EloquentType::make()
#6 /var/www/html/vendor/kiwilan/typescriptable-laravel/src/Commands/TypescriptableModelsCommand.php(28): Kiwilan\\Typescriptable\\Typescriptable::models()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Kiwilan\\Typescriptable\\Commands\\TypescriptableModelsCommand->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"} 
```

### How to reproduce the bug

Just install the mentioned package and give the HasRoles trait to the user model.

### Package Version

latest

### PHP Version

8.1.0

### Which operating systems does with happen with?

Windows, Linux

### Notes

Putting an
```
Log::debug($this->relations);
```
at vendor/kiwilan/typescriptable-laravel/src/Typed/Eloquent/EloquentItem.php:126 I was able to found that this package returns
```
array (
  'roles' => 
  Kiwilan\Typescriptable\Typed\Eloquent\Utils\EloquentRelation::__set_state(array(
     'model' => 'App\\Models\\User',
     'field' => 'roles',
     'isArray' => true,
     'isMorph' => false,
     'type' => NULL,
     'typeTs' => '[]',
  )),
  'permissions' => 
  Kiwilan\Typescriptable\Typed\Eloquent\Utils\EloquentRelation::__set_state(array(
     'model' => 'App\\Models\\User',
     'field' => 'permissions',
     'isArray' => true,
     'isMorph' => false,
     'type' => NULL,
     'typeTs' => '[]',
  )),
)  
```
Idk how to reproduce the error in laravel without this package, but I think this should help.

**Comment by ewilan-riviere** [comment]
I will check this today, thanks for error reporting

**Comment by ewilan-riviere** [comment]
You could use [v1.11.02](https://github.com/kiwilan/typescriptable-laravel/releases/tag/1.11.02), relationships with `laravel-permissions` will be as `any[]`. It's temporary bugfix, I will try to parse it to create TS relationships.

**Comment by Temepest74** [comment]
It solved for now, but I found another small bug. When checking the models, you check even skipped models.
I have a model made with https://github.com/calebporzio/sushi which I doubt you can create a ts types for it, so I added it inside models.skip config array, but I still get 
```
Base table or view not found: 1146 Table 'example_app.external_model' doesn't exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:421)
```

**Comment by ewilan-riviere** [comment]
I will check this too, thanks!

**Comment by Temepest74** [comment]
It looks like it work alright now, thank you
